services:
  site:
    build: .
    container_name: divergent-site
    restart: always

    healthcheck:
      test: curl --fail -s http://localhost:3000
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s

    labels:
      - traefik.enable=true

      # Service
      - traefik.http.services.site.loadbalancer.server.port=3000

      # Router
      - traefik.http.routers.site.rule=Host(`diver-gent.ugent.be`)
      - traefik.http.routers.site.service=divergent-site
      - traefik.http.routers.site.entrypoints=https
      - traefik.http.routers.site.tls=true
      - traefik.http.routers.site.tls.certresolver=letsencrypt

    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true